// Curated icon set for habits. Keeping an explicit map (rather than importing
// all of lucide) keeps the bundle small and the picker tidy.

import {
  Apple,
  Bath,
  BedDouble,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  Carrot,
  CigaretteOff,
  Code,
  Coffee,
  Droplet,
  Dumbbell,
  Flame,
  Flower2,
  Footprints,
  Glasses,
  GraduationCap,
  Guitar,
  Heart,
  Languages,
  Leaf,
  type LucideIcon,
  Moon,
  Mountain,
  Music,
  Paintbrush,
  Pencil,
  PiggyBank,
  Pill,
  Salad,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Target,
  Timer,
  Trophy,
  Waves,
  Wind,
} from "lucide-react";

export const HABIT_ICONS: Record<string, LucideIcon> = {
  dumbbell: Dumbbell,
  bookOpen: BookOpen,
  droplet: Droplet,
  pill: Pill,
  brain: Brain,
  heart: Heart,
  bed: BedDouble,
  footprints: Footprints,
  apple: Apple,
  coffee: Coffee,
  code: Code,
  music: Music,
  pencil: Pencil,
  briefcase: Briefcase,
  sparkles: Sparkles,
  sun: Sun,
  moon: Moon,
  leaf: Leaf,
  bike: Bike,
  noSmoking: CigaretteOff,
  piggyBank: PiggyBank,
  camera: Camera,
  paintbrush: Paintbrush,
  languages: Languages,
  graduation: GraduationCap,
  carrot: Carrot,
  salad: Salad,
  bath: Bath,
  flower: Flower2,
  mountain: Mountain,
  waves: Waves,
  wind: Wind,
  sprout: Sprout,
  target: Target,
  flame: Flame,
  trophy: Trophy,
  star: Star,
  smile: Smile,
  glasses: Glasses,
  guitar: Guitar,
  timer: Timer,
};

export const HABIT_ICON_NAMES = Object.keys(HABIT_ICONS);

export const DEFAULT_HABIT_ICON = "target";

export function habitIcon(name: string | null | undefined): LucideIcon {
  return (name && HABIT_ICONS[name]) || HABIT_ICONS[DEFAULT_HABIT_ICON];
}

// A friendly palette for habit accent colors (shared with the picker).
export const HABIT_COLORS = [
  "#f5c451",
  "#6366f1",
  "#ec4899",
  "#10b981",
  "#3b82f6",
  "#8b5cf6",
  "#ef4444",
  "#14b8a6",
  "#f97316",
  "#06b6d4",
  "#84cc16",
  "#a855f7",
];
